[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd gamemaster-assistant && npm install && cd backend && npm install && cd ../frontend && npm install"]

[phases.build]
cmds = ["cd gamemaster-assistant && npm run build"]

[start]
cmd = "cd gamemaster-assistant && npm start"
